apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
  labels:
    app: auth-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      labels:
        app: auth-service
    spec:
      containers:
        - name: auth-service
          # ECR 이미지 주소로 수정
          image: 730335665695.dkr.ecr.ap-northeast-2.amazonaws.com/auth-service:latest
          # EKS에서는 Always를 권장
          imagePullPolicy: Always
          lifecycle:
            preStop:
              exec:
                command: [ "sh", "-c", "sleep 5" ]
          ports:
            - containerPort: 8886
          env:
            - name: BPL_JVM_THREAD_COUNT
              value: "50" 
            - name: SPRING_DATASOURCE_URL
              # value: jdbc:mysql://10.0.3.143:3306/auth?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC&characterEncoding=UTF-8
              value: jdbc:mysql://polar-mysql:3306/auth?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC&characterEncoding=UTF-8